### ISSUE TITLE
Support for multiline import/exports

### ISSUE THREAD

**Issue by fox1t** [beenotung/fix-esm-import-path#12]
Again me! Working on the big monorepo, I found another limitation. This snippet has not been checked and has been changed by this package.
```ts
import {
  attachExternalOrganizationKMSPolicyToTLFLowRole,
  attachExternalOrganizationKMSPolicyToTLFLowUser,
  attachReplicationKMSPolicyToMRAPRole,
  createExternalOrganizationKMSPolicy,
  createReplicationKMSPolicy,
} from './onboarding';
```
This is due to the multiline import/export.
Adding the following regexp to https://github.com/beenotung/fix-esm-import-path/blob/master/fix-esm-import-path.js#L222, fix the issue:
```ts
    /.*import\s*{[^}]*}\s*from\s*'(.*?)'.*/g,
    /.*import\s*{[^}]*}\s*from\s*"(.*?)".*/g,
    /.*export\s*{[^}]*}\s*from\s*'(.*?)'.*/g,
    /.*export\s*{[^}]*}\s*from\s*"(.*?)".*/g,
```
Let me know if you want me to open a PR.

**Comment by beenotung** [comment]
Thanks for the suggestion :heart: It is released in fix-esm-import-path@1.7.0 :rocket: 

Please feel free to re-open the issue if it hasn't solve the issue in your case
