### ISSUE TITLE
Support more than 1 CLI argument?

### ISSUE THREAD

**Issue by egasimus** [beenotung/fix-esm-import-path#3]
`npx -y fix-esm-import-path *.dist.js` only seems to process the first file.

tested with `npx -y fix-esm-import-path file1.dist.js file2.dist.js`.

hacky workaround: `find . -maxdepth 1 -name '*.dist.js' -exec npx -y fix-esm-import-path {} \;`
(replace `.` with your dist dir and `.dist.js` with your dist extension)

**Comment by egasimus** [comment]
otherwise congrats of the 4ish libraries addressing this massice ecosystemic fuckup yours is the only one that seems to work <3

**Comment by egasimus** [comment]
although why does it also modify the sources when only passed 1 compiled file at a time?

**Comment by beenotung** [comment]
It treats the given file as entry point, then process all files directly or indirectly imported by that file as well.

The current implementation only treat the first argument as the entry point, because other files are usually imported by the entry point eventually.
It seems that's not your case?

I will update it to allow multiple entry points

**Comment by beenotung** [comment]
Updated to support multiple entry point, now `npx -y fix-esm-import-path *.dist.js` should process all matched files.

(Released v1.3.1 to npm)

**Comment by egasimus** [comment]
Thanks for your quick response!

In my case I want to preserve the `.ts` sources unmodified - so that the package can be used raw in TS-native environments, such as anything with a dev server these days - and patch only the compiled files. And since I already have a list of those handy, the import crawling becomes superfluous. (Now that you support multiple entry points, maybe you can make that step optional?)

I ended up implementing my own fix [here](https://github.com/hackbg/toolbox/blob/053ef8c1086290811bf071cf939220403c47f3db/izomorf/izomorf.cjs#L300-L333) but apparently it still doesn't cover some edge case, so I added `fix-esm-import-path` after it and my CI passed.

All in all, it became quite tricky to publish TS packages after Node removed automatic extensions from their ESM loader, eh? :/

**Comment by beenotung** [comment]
I see why you need to handle multiple files instead of from a single entryPoint, probably because you're dealing with library package and want to enable tree shrinking.

**Comment by beenotung** [comment]
I'm not sure which feature do you want to be optional. 

Do you mean you want this package to only process given files, but don't recursively process imported files ?

**Comment by beenotung** [comment]
I suppose the compiled js will only import other js files, but it won't import ts files (after compilation).

So if you pass the js files as entry points, the ts files should be unmodified.

**Comment by beenotung** [comment]
This issue should be resolved, feel free to re-open it or create another issue when needed
