### ISSUE TITLE
Support TypeScript `import type`

### ISSUE THREAD

**Issue by devidw** [beenotung/fix-esm-import-path#5]
Hey @beenotung 

Thanks a lot, creating this tool

When using `NodeNext` `import type` imports also need to resolve in `.js` extensions, otherwise ts compiler will throw:

```
gen/api.ts:16:36 - error TS2835: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './configuration.js'?

16 import type { Configuration } from './configuration';
```

I see that these are currently ignored in the script via:

https://github.com/beenotung/fix-esm-import-path/blob/aa831df0a0e7561d863e371a4bcf39e84ecf58dd/fix-esm-import-path.js#L210

When I am removing this line, they are fixed as well.

Am I missing something, why we don't want to replace those as well by default?

In this case, we could maybe expose a CLI option to include/exclude those imports, if this makes sense to you?

🙌

**Comment by beenotung** [comment]
The program is not modifying import type because those import are supposed to be removed when transpiled into js file.

Is it the case that, your transpiler / bundler is preserving the import type statements in the output?

**Comment by devidw** [comment]
Running with bare bones, vanilla typescript compiler:

```
"typescript": "^5.0.0"
```

_tsconfig.json_
```json
{
	"compilerOptions": {
		"strict": true,
		"target": "ESNext",
		"module": "NodeNext",
		"moduleResolution": "nodenext"
	}
}
```

_build command_
```console
tsc
```

Which will throw for all non-types imports (fixed by this package), but will still throw for type-imports:

```plain
gen/common.ts:17:34 - error TS2835: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './base.js'?

17 import type { RequestArgs } from "./base";
```

**Comment by beenotung** [comment]
I'm working on `--process-import-type` and `--preserve-import-type` flag to address this issue.

I'm thinking what should the default behavior be. It seems easier to process them by default, and only preserve them as is if the project is not affected by this issue and want to minimize "git changes"

**Comment by devidw** [comment]
Wonderful, thanks a lot ✨
Yeah, that sounds good

**Comment by beenotung** [comment]
The patch is released in v1.4.0 🎉 
Thanks for your suggestion.
Please feel free to reopen this issue if it is not fixed in your case

**Comment by devidw** [comment]
Wow, that was fast, thanks a bunch - works great! 🙏

**Comment by alonesuperman** [comment]
> _tsconfig.json_
> 
> ```json
> {
> 	"compilerOptions": {
> 		"strict": true,
> 		"target": "ESNext",
> 		"module": "NodeNext",
> 		"moduleResolution": "nodenext"
> 	}
> }
> ```


maybe u can change to `"moduleResolution":"Bundler"`
