### ISSUE TITLE
Tries to convert comments that may cause issues

### ISSUE THREAD

**Issue by treeder** [beenotung/fix-esm-import-path#7]
eg, this is one of the files:

```
// import CodaBarWriter from './oned/CodaBarWriter'
```

And it errors out:

```
[scanImport] File not found: {
  srcFile: 'esm/core/MultiFormatWriter.js',
  importName: 'esm/core/oned/CodaBarWriter',
  importCode: "// import CodaBarWriter from './oned/CodaBarWriter'",
  name: './oned/CodaBarWriter'
}
```

**Comment by beenotung** [comment]
Thanks for reporting the bug. This issued should be fixed and released update as  fix-esm-import-path@1.4.2 :rocket: 

If you're still having problem with the updated version, please feel free to re-open the issue :)
