### ISSUE TITLE
Error when importing node:fs/promises

### ISSUE THREAD

**Issue by 727021** [beenotung/fix-esm-import-path#8]
![image](https://github.com/beenotung/fix-esm-import-path/assets/1834544/d3973b8c-9dde-48b0-89d6-63e6502d74e9)

I get an error if I have a file that imports `node:fs/promises`. Removing that import or replacing it with
```ts
import { promises } from 'node:fs'
const { writeFile } = promises
```
fixes the issue, but I'd like to be able to just import `node:fs/promises` directly.

Other `node:` imports, including `node:fs`, work correctly.

**Comment by beenotung** [comment]
Thanks for the report. This issue is fixed and released as fix-esm-import-path@1.4.1 :rocket: 

Feel free to re-open the issue if you're still having problem with the updated version :)
