### ISSUE TITLE
Does not work with import assertions

### ISSUE THREAD

**Issue by mrjackyliang** [beenotung/fix-esm-import-path#9]
<img width="696" alt="Screenshot 2023-12-03 at 10 00 35 PM" src="https://github.com/beenotung/fix-esm-import-path/assets/9779803/954400d3-e80b-40e6-a7d8-843204616394">

I have a feeling it's because the regular expression to detect these imports are incorrect.

**Comment by beenotung** [comment]
Thanks for the report.

This issue should be fixed in v1.5.0 :rocket:

Feel free to re-open this issue if the problem persist in your case
